### ISSUE TITLE
Update tracing-api to support the Geth tracing API (debug_traceTransaction)

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/tracing-api#9]
The Vulcanize tracing API needs to support the Geth tracing API.

You can see the Geth tracing API in action on Etherscan: here it is showing the "Geth Debug Trace":
https://etherscan.io/vmtrace?txhash=0xab6b8315187d3333f2cad87eb861203c856b6cb997b0d58f2d96b6ea1a42c258

Please confirm that we would be able to support similar results by having support only for the `debug_traceTransaction` call.

**Comment by stellarmagnet** [comment]
@ramilexe as discussed in the call today, it is fine to work on this issue without needing to enhance the cache.

**Comment by ramilexe** [comment]
Got it

**Comment by ramilexe** [comment]
Yes @i-norden
